version: '3'
services:
  mongodb_container:
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      MONGO_REPLICA_HOST: host.docker.internal
      INIT_WAIT_SEC: 5
    ports:
      - 27017:27017

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - ../backend:/app/backend
      - ../provision/evironment/backend/.env:/app/backend/.env
    ports:
      - 4000:4000
    depends_on:
      - mongodb_container
      
  client:
    build:
      context: ../client
      dockerfile: Dockerfile
    volumes:
      - ../client:/app/client
      - ../provision/evironment/client/.env:/app/client/.env
    ports:
      - 8080:80
    depends_on:
      - backend